//
// Copyright (c) 2025-2026 Jeff Garzik
//
// This file is part of the posixutils-rs project covered under
// the MIT License.  For the full license text, please see the LICENSE
// file in the root directory of this project.
// SPDX-License-Identifier: MIT
//
// Architecture-independent code generation interface
//

use crate::arch::lir::{Directive, EmitAsm, LirInst, Symbol};
use crate::arch::DEFAULT_LIR_BUFFER_CAPACITY;
use crate::float::FloatVal;
use crate::ir::{Function, Initializer, Instruction, Module, Opcode, Pseudo, PseudoId};
use crate::target::{Os, Target};
use crate::types::TypeTable;

// Shared Helper Types

/// Unary integer operation type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnaryOp {
    Neg,
    Not,
}

/// Byte-swap size
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BswapSize {
    B16,
    B32,
    B64,
}

// Constants

/// c17 version string for assembly header
pub const C17_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Generate header comment lines for assembly output (GCC-style)
/// Returns a vector of comment strings to be emitted
pub fn generate_header_comments(target: &Target) -> Vec<String> {
    let mut comments = Vec::new();

    // Target triple (normalized format)
    let os_triple = match target.os {
        crate::target::Os::Linux => "unknown-linux-gnu",
        crate::target::Os::MacOS => "apple-darwin",
        crate::target::Os::FreeBSD => "unknown-freebsd",
    };

    // Compiler identification with target
    comments.push(format!(
        "Generated by c17 {} ({}-{})",
        C17_VERSION, target.arch, os_triple
    ));

    comments
}

/// Check if a function uses variadic arguments (contains VaStart opcode)
pub fn is_variadic_function(func: &Function) -> bool {
    for block in &func.blocks {
        for insn in &block.insns {
            if matches!(insn.op, Opcode::VaStart) {
                return true;
            }
        }
    }
    false
}

/// Escape a string for assembly output (.ascii/.asciz directives)
/// Non-printable and non-ASCII characters are escaped as octal byte sequences.
pub fn escape_string(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            c if c.is_ascii_graphic() || c == ' ' => result.push(c),
            c => {
                // String literals represent raw byte values (0-255).
                // Emit as single octal byte, not UTF-8 encoded.
                if (c as u32) <= 255 {
                    result.push_str(&format!("\\{:03o}", c as u8));
                } else {
                    for byte in c.to_string().as_bytes() {
                        result.push_str(&format!("\\{:03o}", byte));
                    }
                }
            }
        }
    }
    result
}

// CodeGenBase - Generic Code Generation Infrastructure

/// Common code generation state shared between all architectures.
/// Generic over the LIR instruction type I, enabling type-safe architecture-specific
/// instruction buffers while sharing common infrastructure.
pub struct CodeGenBase<I: LirInst> {
    /// Target platform information
    pub target: Target,
    /// Output buffer for emitted assembly
    pub output: String,
    /// LIR instruction buffer for deferred emission and peephole optimization
    pub lir_buffer: Vec<I>,
    /// Current function name (for label generation)
    pub current_fn: String,
    /// Whether to emit basic unwind tables (cfi_startproc/cfi_endproc)
    pub emit_unwind_tables: bool,
    /// A source position for the function being emitted, for a backend
    /// diagnostic that has no nearer one -- `crate::abi::slot_bytes` and
    /// `crate::arch::regalloc::grow_frame` report against it. Set from
    /// `crate::arch::func_pos` at the top of each `emit_function`.
    pub func_pos: crate::diag::Position,
    /// Last emitted source line (for avoiding duplicate .loc directives)
    pub last_debug_line: u32,
    /// Last emitted source file index
    pub last_debug_file: u16,
    /// Whether to emit debug info (.file/.loc directives)
    pub emit_debug: bool,
    /// Whether the output has to be able to live in a shared object, which is
    /// what selects the thread-local access model. Set for `-shared` and for
    /// `-fPIC`; see [`CodeGenBase::use_tls_dynamic`].
    pub shared_mode: bool,
    /// `-fverbose-asm`: annotate the generated instructions.
    pub verbose_asm: bool,
    /// Trailing comments to hang off individual LIR instructions, by their
    /// index in `lir_buffer`.
    ///
    /// A comment cannot travel *on* the instruction: `X86Inst` and
    /// `Aarch64Inst` are plain enums with no metadata field, and `EmitAsm`
    /// sees only the instruction and the target. Keeping the text beside the
    /// buffer lets `emit_all` append it to the line it has just written,
    /// without a new field on either enum or a change to any `emit` arm.
    pub lir_comments: std::collections::HashMap<usize, String>,
    /// What `-g` needs to say about each function: its extent, and the
    /// parameters and locals inside it with where they live.
    ///
    /// Collected as the functions are emitted, because that is the only point
    /// at which a variable's home is known -- the register allocator's decision
    /// is per-function and is not kept afterwards.
    pub fn_dies: Vec<super::dwarf::FnDie>,
}

impl<I: LirInst + EmitAsm> CodeGenBase<I> {
    /// Create a new CodeGenBase for the given target
    pub fn new(target: Target) -> Self {
        Self {
            target,
            output: String::new(),
            lir_buffer: Vec::with_capacity(DEFAULT_LIR_BUFFER_CAPACITY),
            current_fn: String::new(),
            emit_unwind_tables: true,
            func_pos: crate::diag::Position::default(),
            last_debug_line: 0,
            last_debug_file: 0,
            emit_debug: false,
            shared_mode: false,
            verbose_asm: false,
            lir_comments: std::collections::HashMap::new(),
            fn_dies: Vec::new(),
        }
    }

    /// Attach `text` to the next instruction pushed, as a trailing comment.
    ///
    /// Does nothing unless `-fverbose-asm` asked for it.
    pub fn annotate_next(&mut self, text: String) {
        if self.verbose_asm {
            self.lir_comments.insert(self.lir_buffer.len(), text);
        }
    }

    /// Whether thread-local access must use the dynamic model.
    ///
    /// Initial Exec resolves the offset through the GOT at load time, which
    /// requires the object's thread-locals to fit in the loader's static-TLS
    /// surplus -- so a library `dlopen`ed later with a large block is rejected.
    /// Only the dynamic model has no such limit.
    ///
    /// `shared_mode` is set for `-shared` and for `-fPIC`, which asks for code
    /// that can live in a shared object -- the same requirement. It is *not*
    /// set for `-fPIE` or the PIE default, because a PIE executable still
    /// resolves its own thread-locals at link time.
    ///
    /// Must agree with the condition `ir::tls::expand_dynamic_tls` was given,
    /// since that pass is what puts the address computation where the register
    /// allocator can see it.
    pub fn use_tls_dynamic(&self) -> bool {
        self.tls_access() == crate::target::TlsAccess::ElfDescriptor
    }

    /// How this target obtains a thread-local's address; see
    /// [`crate::target::Target::tls_access`], which `ir::tls` asks too.
    pub fn tls_access(&self) -> crate::target::TlsAccess {
        self.target.tls_access(self.shared_mode)
    }

    /// Whether a thread-local access must use the Initial Exec model rather
    /// than Local Exec.
    ///
    /// Local Exec fixes the offset from the thread pointer at link time, which
    /// only holds for the main executable and for a thread-local defined in
    /// this object. Code for a shared object (`shared_mode`), and any symbol
    /// defined elsewhere -- which is what `is_extern` reports -- needs the
    /// offset loaded from the GOT instead. On Linux shared code takes the
    /// descriptor model before it gets here; on FreeBSD, which stays with the
    /// static models, leaving `shared_mode` out put Local Exec in a shared
    /// object -- `%fs:t@TPOFF`, a relocation `ld -shared` refuses.
    pub fn use_tls_ie(&self, is_extern: bool) -> bool {
        self.use_tls_dynamic() || is_extern || self.shared_mode
    }

    pub fn push_lir(&mut self, inst: I) {
        self.lir_buffer.push(inst);
    }

    pub fn push_directive(&mut self, dir: Directive) {
        self.lir_buffer.push(I::from_directive(dir));
    }

    /// Emit all buffered LIR instructions to the output string
    pub fn emit_all(&mut self) {
        let comment = asm_comment_prefix(&self.target);
        for (idx, inst) in self.lir_buffer.iter().enumerate() {
            let before = self.output.len();
            inst.emit(&self.target, &mut self.output);
            let Some(text) = self.lir_comments.get(&idx) else {
                continue;
            };
            // One instruction can emit several lines, or none. Hang the
            // comment off the last line that has anything on it.
            if self.output.len() <= before || !self.output.ends_with('\n') {
                continue;
            }
            self.output.pop();
            if self.output[before..].trim().is_empty() {
                self.output.push('\n');
                continue;
            }
            self.output.push_str(&format!(" {} {}\n", comment, text));
        }
    }

    /// Clear LIR buffer (for reuse between functions)
    pub fn clear_lir(&mut self) {
        self.lir_buffer.clear();
        self.lir_comments.clear();
    }

    /// Reset debug state for new module
    pub fn reset_debug_state(&mut self) {
        self.last_debug_line = 0;
        self.last_debug_file = 0;
    }

    /// Emit file header with compiler info
    pub fn emit_header(&mut self) {
        for comment in generate_header_comments(&self.target) {
            self.push_directive(Directive::Comment(comment));
        }
        self.push_directive(Directive::Text);
    }

    /// Emit .loc directive for source line tracking
    /// Returns true if a directive was emitted
    pub fn emit_loc(&mut self, insn: &Instruction) -> bool {
        if !self.emit_debug {
            return false;
        }
        if let Some(pos) = &insn.pos {
            let file = pos.stream + 1; // DWARF file indices start at 1
            let line = pos.line;
            if line != self.last_debug_line || file != self.last_debug_file {
                self.push_directive(Directive::loc(file.into(), line, pos.col.into()));
                self.last_debug_line = line;
                self.last_debug_file = file;
                return true;
            }
        }
        false
    }

    /// Emit the `.loc` that covers a function's prologue.
    ///
    /// `emit_loc` runs per instruction as the blocks are emitted, so the first
    /// `.loc` of a function landed *after* the prologue -- and a function's
    /// entry address then had no row in the line table at all. `break f` asks
    /// for exactly that address, so gdb answered "No line number information
    /// available" and gave up on the whole function, even though every later
    /// address in it was covered.
    ///
    /// gcc emits the opening line before `.cfi_startproc` for this reason. The
    /// position comes from the first instruction that carries one, which is the
    /// same position the old first `.loc` used; `emit_loc`'s own de-duplication
    /// keeps it from being repeated once the blocks start.
    pub fn emit_function_entry_loc(&mut self, func: &Function) {
        if !self.emit_debug {
            return;
        }
        let Some(pos) = func
            .blocks
            .iter()
            .flat_map(|b| b.insns.iter())
            .find_map(|i| i.pos.as_ref())
        else {
            return;
        };
        let file = pos.stream + 1; // DWARF file indices start at 1
        self.push_directive(Directive::loc(file.into(), pos.line, pos.col.into()));
        self.last_debug_line = pos.line;
        self.last_debug_file = file;
    }

    /// `.weak` and visibility for symbols this unit only declares.
    ///
    /// A defined symbol carries these on its own definition; a declared one has
    /// no definition to hang them on, so they are emitted standalone. Without
    /// this, `extern int f(void) __attribute__((weak));` produced a strong
    /// reference and an absent `f` was a link error rather than a null pointer.
    pub fn emit_declared_symbol_attrs(&mut self, module: &Module) {
        for (name, attrs) in &module.declared_symbol_attrs {
            if module.functions.iter().any(|f| f.name == *name)
                || module.globals.iter().any(|g| g.name == *name)
            {
                continue;
            }
            if attrs.weak {
                self.push_directive(Directive::Weak(
                    Symbol::global(name),
                    crate::arch::lir::WeakKind::Reference,
                ));
            }
            if let Some(how) = &attrs.visibility {
                self.push_directive(Directive::Visibility(Symbol::global(name), how.clone()));
            }
        }
    }

    pub fn emit_global(&mut self, global: &crate::ir::GlobalDef, types: &TypeTable) {
        let size = types.size_bytes(global.typ) as u64;
        let size = if size == 0 { 8 } else { size }; // Default to 8 bytes
        let align = global_alignment(global, types);

        if global.is_thread_local && self.target.os == Os::MacOS {
            self.emit_macho_thread_local(global, size, align);
            return;
        }

        // Anonymous compound-literal globals (name starts with '.') are addressed
        // as locals via `.LC`-style labels — they must remain ordinary data labels.
        let is_local_label = global.name.starts_with('.');

        // Route zero-initialized non-TLS globals to BSS-class storage. This costs
        // nothing in the object file and lets the kernel lazy-allocate pages.
        //
        // The path also handles tentative definitions (`int x;`) and explicit
        // zero-initializers (`int x = 0;` / `static int arr[1000] = {0};`).
        // A named section is the program's decision and overrides every rule
        // below, including the zero-initialized fast path: `.comm` places the
        // object wherever the linker likes, which is exactly what
        // `section("...")` is asking not to happen.
        let named_section = global.symbol_attrs.section.clone();

        // `weak` and an explicit visibility are in the same position as a
        // named section: a common symbol carries neither, and the fast path
        // returns before the directives that would. A hidden variable escaping
        // as default-visibility is an ABI change, not a cosmetic one, so these
        // go the long way round into `.bss` -- which is what gcc emits too.
        //
        // `const` is excluded outright: a read-only object belongs in
        // `.rodata`, and BSS-class storage is writable. gcc puts both the
        // tentative and the initialized `const` there.
        let zero_init = !global.is_thread_local
            && !global.is_const
            && size > 0
            && global.init.is_all_zero()
            && named_section.is_none()
            && !global.symbol_attrs.weak
            && global.symbol_attrs.visibility.is_none();
        if zero_init && !is_local_label {
            if global.is_static {
                self.push_directive(Directive::bss_local(&global.name, size, align));
            } else {
                // A *definition*, not a common symbol. `.comm` merges across
                // translation units, so two definitions of one object linked
                // silently where C17 6.9p5 allows one -- and gcc, which has
                // defaulted to `-fno-common` since 10, reports it.
                self.push_directive(Directive::bss_global(&global.name, size, align));
            }
            return;
        }

        // Select appropriate section for TLS vs regular data
        if let Some(name) = &named_section {
            self.push_directive(Directive::NamedSection {
                name: name.clone(),
                executable: false,
                // Const data that needs relocations cannot be mapped read-only
                // until the dynamic linker has run, so it is writable in the
                // object the same way `.data.rel.ro` is.
                writable: !global.is_const || global.init.has_reloc(),
            });
        } else if global.is_thread_local {
            if matches!(global.init, Initializer::None) {
                // Uninitialized TLS: .tbss section
                self.push_directive(Directive::Tbss);
            } else {
                // Initialized TLS: .tdata section
                self.push_directive(Directive::Tdata);
            }
        } else if global.is_const {
            // Read-only data. If the initializer contains symbol addresses, the
            // dynamic linker has to fix them up: put it in `.data.rel.ro` so
            // it can be mapped read-only after relocations are applied.
            if global.init.has_reloc() {
                self.push_directive(Directive::DataRelRo);
            } else {
                self.push_directive(Directive::Rodata);
            }
        } else {
            // Regular data section
            self.push_directive(Directive::Data);
        }

        // Global visibility (if not static and not a `.LC...`-style local label)
        if !global.is_static && !is_local_label {
            if global.symbol_attrs.weak {
                self.push_directive(Directive::Weak(
                    Symbol::global(&global.name),
                    crate::arch::lir::WeakKind::Definition,
                ));
            } else {
                self.push_directive(Directive::global(&global.name));
            }
        }
        if let Some(how) = &global.symbol_attrs.visibility {
            self.push_directive(Directive::Visibility(
                Symbol::global(&global.name),
                how.clone(),
            ));
        }

        // ELF-only type and size (handled by Directive::emit which skips on macOS)
        // TLS objects have TLS type instead of regular object type
        if global.is_thread_local {
            self.push_directive(Directive::type_tls_object(&global.name));
        } else {
            self.push_directive(Directive::type_object(&global.name));
        }
        self.push_directive(Directive::size(&global.name, size));

        // Alignment
        if align > 1 {
            self.push_directive(Directive::Align(align.trailing_zeros()));
        }

        // Label - use local_label for names starting with '.'
        if is_local_label {
            self.push_directive(Directive::local_label(&global.name));
        } else {
            self.push_directive(Directive::global_label(&global.name));
        }

        // Emit initializer
        self.emit_initializer_data(&global.init, size as usize);
    }

    /// A Mach-O thread-local variable: its initial image, and the descriptor
    /// that names it.
    ///
    /// On Darwin the symbol a program refers to is not the storage. `_v`
    /// labels a three-word *descriptor* in `__DATA,__thread_vars` --
    /// `{ __tlv_bootstrap, 0, _v$tlv$init }`: the getter to call, a key dyld
    /// fills in, and the initial image -- and every access calls through it
    /// (see each backend's `emit_tls_addr`). The image itself is
    /// `_v$tlv$init`: initialized data in `__thread_data`, or `.tbss` for a
    /// zero-initialized one, which reserves zero-fill in `__thread_bss`.
    /// This is the layout clang emits, and the one dyld's TLV support and
    /// ld64 expect: ld64 builds each thread's block from the images and
    /// rewrites `@TLVP` references to the descriptors.
    ///
    /// Emitting the variable as plain data, as this used to, gave every
    /// thread the one shared copy -- and an `extern` one, reached through
    /// `@GOTPAGE`, a reference to a thread-local that ld64 rejects.
    ///
    /// Linkage belongs to the descriptor: `.globl`/weak/visibility go on `_v`,
    /// and the image is always a local symbol.
    fn emit_macho_thread_local(&mut self, global: &crate::ir::GlobalDef, size: u64, align: u32) {
        let image = Symbol::global(format!("{}$tlv$init", global.name));
        let zero_fill = global.init.is_all_zero() && global.symbol_attrs.section.is_none();
        if zero_fill {
            // `.tbss symbol, size, log2(align)` -- the Mach-O zero-fill form
            // for a thread-local image; it places the symbol in
            // `__DATA,__thread_bss` itself.
            self.push_directive(Directive::ThreadZerofill {
                sym: image.clone(),
                size,
                align_log2: align.max(1).trailing_zeros(),
            });
        } else {
            self.push_directive(Directive::Tdata);
            if align > 1 {
                self.push_directive(Directive::Align(align.trailing_zeros()));
            }
            self.push_directive(Directive::global_label(image.name.clone()));
            self.emit_initializer_data(&global.init, size as usize);
        }

        self.push_directive(Directive::ThreadVars);
        if !global.is_static {
            if global.symbol_attrs.weak {
                self.push_directive(Directive::Weak(
                    Symbol::global(&global.name),
                    crate::arch::lir::WeakKind::Definition,
                ));
            } else {
                self.push_directive(Directive::global(&global.name));
            }
        }
        if let Some(how) = &global.symbol_attrs.visibility {
            self.push_directive(Directive::Visibility(
                Symbol::global(&global.name),
                how.clone(),
            ));
        }
        // Three pointers; keep them pointer-aligned whatever precedes them.
        self.push_directive(Directive::Align(3));
        self.push_directive(Directive::global_label(&global.name));
        self.push_directive(Directive::QuadSym(Symbol::global("_tlv_bootstrap")));
        self.push_directive(Directive::Quad(0));
        self.push_directive(Directive::QuadSym(image));
    }

    /// Emit a floating constant as `size` bytes in the target's format.
    ///
    /// `size` is the storage size of the declared type, so it selects the
    /// format: 2 is `_Float16`, 4 is binary32, 8 is binary64, and 16 is
    /// whatever `long double` means here -- binary128 on aarch64, an x87
    /// 80-bit extended padded to 16 bytes on x86_64.
    fn emit_float_initializer(&mut self, val: FloatVal, size: usize) {
        match size {
            2 => {
                // IEEE-754 binary16 is the same encoding on both targets; the
                // two backends carry byte-identical copies of this conversion.
                let bits = crate::arch::aarch64::f64_to_f16_bits(val.to_f64());
                self.push_directive(Directive::Short(bits as i64));
            }
            4 => {
                let bits = (val.to_f64() as f32).to_bits();
                self.push_directive(Directive::Long(bits as i64));
            }
            16 => {
                // The only width where the literal's full precision matters:
                // both encodings are produced from the exact value rather than
                // from a double, so `LDBL_MAX` is not already infinity here.
                let (lo, hi) = match self.target.arch {
                    crate::target::Arch::Aarch64 => val.to_f128_bits(),
                    crate::target::Arch::X86_64 => {
                        let bytes = val.to_x87_bytes();
                        let mut lo = [0u8; 8];
                        let mut hi = [0u8; 8];
                        lo.copy_from_slice(&bytes[..8]);
                        hi.copy_from_slice(&bytes[8..]);
                        (u64::from_le_bytes(lo), u64::from_le_bytes(hi))
                    }
                };
                self.push_directive(Directive::Quad(lo as i64));
                self.push_directive(Directive::Quad(hi as i64));
            }
            _ => {
                // double - emit as 64-bit IEEE 754
                self.push_directive(Directive::Quad(val.to_f64().to_bits() as i64));
            }
        }
    }

    /// Emit data for an initializer, recursively handling complex types
    pub fn emit_initializer_data(&mut self, init: &Initializer, size: usize) {
        match init {
            Initializer::None => {
                // Zero-fill
                self.push_directive(Directive::Zero(size));
            }
            Initializer::Int(val) => {
                if size > 8 {
                    // 128-bit: emit as two quads (little-endian: lo then hi)
                    let lo = *val as i64;
                    let hi = (*val >> 64) as u64 as i64;
                    self.push_directive(Directive::Quad(lo));
                    self.push_directive(Directive::Quad(hi));
                } else {
                    match size {
                        1 => self.push_directive(Directive::Byte(*val as i64)),
                        2 => self.push_directive(Directive::Short(*val as i64)),
                        4 => self.push_directive(Directive::Long(*val as i64)),
                        _ => self.push_directive(Directive::Quad(*val as i64)),
                    }
                }
            }
            Initializer::Float(val) => self.emit_float_initializer(*val, size),
            Initializer::Float128(val) => {
                // No target check: the type already said binary128.
                let (lo, hi) = val.to_f128_bits();
                self.push_directive(Directive::Quad(lo as i64));
                self.push_directive(Directive::Quad(hi as i64));
            }
            Initializer::String(s) => {
                // Emit string as .ascii (without null terminator)
                // Then zero-fill the remaining bytes (which includes the null terminator)
                //
                // Truncated to the object's own size first. A string literal
                // longer than the array it initializes is a constraint
                // violation that gcc accepts with a warning and truncates --
                // and emitting all of it wrote *past* the object: with
                // `const char a[2][3] = { "1234", "xyz" };` the excess `4`
                // landed on the second row, and
                // `struct { char n[3]; int tag; } s = { "wxyz", 7 };` pushed
                // `tag` one byte along and read back 1792 instead of 7.
                //
                // Each char in the parsed payload represents one C byte
                // (0-255), so `chars()` counts and truncates in bytes where
                // `len()` would count UTF-8.
                //
                // A size of zero means the object has no bound of its own --
                // a flexible array member, `struct { char c; char f[]; }`,
                // whose extent the initializer is what establishes. There is
                // nothing to truncate to, so the literal is emitted whole.
                let room = if size == 0 { usize::MAX } else { size };
                let kept: String = s.chars().take(room).collect();
                let bytes_emitted = kept.chars().count();
                self.push_directive(Directive::Ascii(escape_string(&kept)));
                if size == 0 {
                    // Unbounded: the terminator is part of what the
                    // initializer establishes, so it is emitted rather than
                    // zero-filled. gcc writes `.string "wx"` here -- four
                    // bytes for `struct { char c; char f[]; } = { 'o', "wx" }`
                    // -- and the wide encodings below already did this, so
                    // leaving it out made the narrow one the odd case and an
                    // unbounded array came back without its `\0`.
                    self.push_directive(Directive::Zero(1));
                } else if size > bytes_emitted {
                    self.push_directive(Directive::Zero(size - bytes_emitted));
                }
            }
            Initializer::WideString(s) => {
                // Emit wide string as sequence of 4-byte values (wchar_t = int)
                // -- at most as many as fit, for the reason `String` truncates.
                // A flexible array member has no bound; see `String`.
                let room = if size == 0 { usize::MAX } else { size / 4 };
                let mut emitted = 0;
                for ch in s.chars().take(room) {
                    self.push_directive(Directive::Long(ch as i64));
                    emitted += 4;
                }
                // The null terminator is part of the value only when there is
                // room for it: `wchar_t w[3] = L"abc"` holds no terminator.
                if size == 0 || emitted + 4 <= size {
                    self.push_directive(Directive::Long(0));
                    emitted += 4;
                }
                if size > emitted {
                    self.push_directive(Directive::Zero(size - emitted));
                }
            }
            Initializer::Utf16String(units) => {
                // char16_t: 2 bytes per code unit.
                // A flexible array member has no bound; see `String`.
                let room = if size == 0 { usize::MAX } else { size / 2 };
                let mut emitted = 0;
                for &u in units.iter().take(room) {
                    self.push_directive(Directive::Short(u as i64));
                    emitted += 2;
                }
                if size == 0 || emitted + 2 <= size {
                    self.push_directive(Directive::Short(0));
                    emitted += 2;
                }
                if size > emitted {
                    self.push_directive(Directive::Zero(size - emitted));
                }
            }
            Initializer::Utf32String(units) => {
                // char32_t: 4 bytes per code point.
                // A flexible array member has no bound; see `String`.
                let room = if size == 0 { usize::MAX } else { size / 4 };
                let mut emitted = 0;
                for &u in units.iter().take(room) {
                    self.push_directive(Directive::Long(u as i64));
                    emitted += 4;
                }
                if size == 0 || emitted + 4 <= size {
                    self.push_directive(Directive::Long(0));
                    emitted += 4;
                }
                if size > emitted {
                    self.push_directive(Directive::Zero(size - emitted));
                }
            }
            Initializer::Array {
                elem_size,
                total_size,
                elements,
            } => {
                // Emit array elements with gaps filled by zeros
                let mut current_offset = 0usize;

                for (offset, elem_init) in elements {
                    // Zero-fill gap before this element
                    if *offset > current_offset {
                        self.push_directive(Directive::Zero(*offset - current_offset));
                    }

                    // Emit element
                    self.emit_initializer_data(elem_init, *elem_size);
                    current_offset = offset + elem_size;
                }

                // Zero-fill remaining space
                if *total_size > current_offset {
                    self.push_directive(Directive::Zero(*total_size - current_offset));
                }
            }
            Initializer::Struct { total_size, fields } => {
                // Emit struct fields with gaps filled by zeros
                let mut current_offset = 0usize;

                for (offset, field_size, field_init) in fields {
                    // Zero-fill gap before this field
                    if *offset > current_offset {
                        self.push_directive(Directive::Zero(*offset - current_offset));
                    }

                    // Emit field
                    self.emit_initializer_data(field_init, *field_size);
                    current_offset = offset + field_size;
                }

                // Zero-fill remaining space
                if *total_size > current_offset {
                    self.push_directive(Directive::Zero(*total_size - current_offset));
                }
            }
            Initializer::SymAddr(name) => {
                let sym = if name.starts_with('.') {
                    Symbol::local(name.clone())
                } else {
                    Symbol::global(name.clone())
                };
                self.push_directive(Directive::QuadSym(sym));
            }
            Initializer::SymAddrOffset(name, offset) => {
                let sym = if name.starts_with('.') {
                    Symbol::local(name.clone())
                } else {
                    Symbol::global(name.clone())
                };
                self.push_directive(Directive::QuadSymOffset(sym, *offset));
            }
        }
    }

    /// Emit the `.init_array` / `.fini_array` entries for every function
    /// carrying a `constructor` or `destructor` attribute.
    ///
    /// Each entry is a pointer-sized slot holding the function's address, in
    /// its own section directive: the linker concatenates them, and the C
    /// runtime walks the resulting array. A function may carry both
    /// attributes, so it can contribute an entry to each array rather than
    /// choosing between them.
    ///
    /// Entries are emitted in run order: prioritized first, ascending, then
    /// the unprioritized ones in declaration order. ELF encodes that in the
    /// section name and the linker sorts for us, but Mach-O has no priority to
    /// encode -- `__mod_init_func` is run in the order the pointers appear --
    /// so on that target emission order *is* the ordering, and a priority
    /// meant nothing until it decided this order. Terminators need no separate
    /// rule: both formats run them in reverse, so the same array order gives
    /// the same reversal.
    pub fn emit_init_arrays(&mut self, functions: &[crate::ir::Function]) {
        // Pointer alignment, as a power of two; both supported targets are
        // 64-bit.
        const PTR_ALIGN_LOG2: u32 = 3;

        // An inline definition provides no external definition (C99 6.7.4p6),
        // so the body-emitting loops skip it and there is no such symbol to
        // point at. Naming it here produced an entry that failed to link.
        let defined = || functions.iter().filter(|f| f.emit);

        // An absent priority runs last, and a stable sort leaves equal
        // priorities in declaration order.
        fn ordered(mut v: Vec<(Option<u16>, &str)>) -> Vec<(Option<u16>, &str)> {
            v.sort_by_key(|(priority, _)| priority.unwrap_or(u16::MAX));
            v
        }

        let constructors = ordered(
            defined()
                .filter_map(|f| f.constructor.map(|p| (p, f.name.as_str())))
                .collect(),
        );
        let destructors = ordered(
            defined()
                .filter_map(|f| f.destructor.map(|p| (p, f.name.as_str())))
                .collect(),
        );

        let emitted_any = !constructors.is_empty() || !destructors.is_empty();
        for (entries, section) in [
            (constructors, Directive::InitArray as fn(_) -> Directive),
            (destructors, Directive::FiniArray as fn(_) -> Directive),
        ] {
            for (priority, name) in entries {
                self.push_directive(section(priority));
                self.push_directive(Directive::Align(PTR_ALIGN_LOG2));
                self.push_directive(Directive::QuadSym(Symbol::global(name.to_string())));
            }
        }

        // Leave the assembler back in .text, as every other section-switching
        // emitter here does.
        if emitted_any {
            self.push_directive(Directive::Text);
        }
    }

    /// Emit string literals to the rodata section
    pub fn emit_strings(&mut self, strings: &[(String, String)]) {
        if strings.is_empty() {
            return;
        }

        self.push_directive(Directive::Rodata);

        for (label, content) in strings {
            self.push_directive(Directive::local_label(label));
            self.push_directive(Directive::Asciz(escape_string(content)));
        }

        self.push_directive(Directive::Text);
    }

    /// Emit wide string literals to the rodata section
    /// Each character is output as a 4-byte value (wchar_t = int = 4 bytes)
    pub fn emit_wide_strings(&mut self, wide_strings: &[(String, String)]) {
        if wide_strings.is_empty() {
            return;
        }

        self.push_directive(Directive::Rodata);
        // wchar_t is a 4-byte int: two, as a power of two.
        self.push_directive(Directive::Align(2));

        for (label, content) in wide_strings {
            self.push_directive(Directive::local_label(label));
            // Emit each character as a 4-byte value
            for ch in content.chars() {
                self.push_directive(Directive::Long(ch as i64));
            }
            // Null terminator
            self.push_directive(Directive::Long(0));
        }

        self.push_directive(Directive::Text);
    }

    /// Emit `u"..."` literals referenced by address.
    pub fn emit_utf16_strings(&mut self, strings: &[(String, Vec<u16>)]) {
        if strings.is_empty() {
            return;
        }
        self.push_directive(Directive::Rodata);
        self.push_directive(Directive::Align(1)); // char16_t: 2 bytes
        for (label, units) in strings {
            self.push_directive(Directive::local_label(label));
            for &u in units {
                self.push_directive(Directive::Short(u as i64));
            }
            self.push_directive(Directive::Short(0));
        }
        self.push_directive(Directive::Text);
    }

    /// Emit `U"..."` literals referenced by address.
    pub fn emit_utf32_strings(&mut self, strings: &[(String, Vec<u32>)]) {
        if strings.is_empty() {
            return;
        }
        self.push_directive(Directive::Rodata);
        self.push_directive(Directive::Align(2)); // char32_t: 4 bytes
        for (label, units) in strings {
            self.push_directive(Directive::local_label(label));
            for &u in units {
                self.push_directive(Directive::Long(u as i64));
            }
            self.push_directive(Directive::Long(0));
        }
        self.push_directive(Directive::Text);
    }
}

// Inline Assembly Support

/// Trait for architecture-specific inline asm operand formatting.
/// Implementations provide register formatting specific to their architecture.
pub trait AsmOperandFormatter {
    /// The register type for this architecture
    type Reg: Copy;

    /// Return the size modifier characters recognized by this architecture.
    /// e.g., x86: ['b', 'w', 'k', 'q'], aarch64: ['w', 'x']
    fn size_modifiers(&self) -> &'static [char];

    /// Format a register with the given size modifier.
    /// Returns the formatted register string (e.g., "%eax" for x86, "w0" for aarch64).
    fn format_reg_sized(&self, reg: Self::Reg, size_mod: char) -> String;

    /// Format a register at operand-appropriate size (for bare %0, %1 references).
    /// The `size_bits` parameter is the operand's declared size from the constraint.
    fn format_reg_default(&self, reg: Self::Reg, size_bits: u32) -> String;
}

/// One inline-asm operand's resolved location, ready for template
/// substitution. Built once per operand by `emit_inline_asm` on each
/// backend; consumed by `substitute_asm_operands`.
///
/// Exactly one of `reg` or `mem` is meaningful for any given operand:
/// `reg` holds a physical register if the operand resolved to a
/// register substitution, and `mem` holds a pre-formatted operand
/// string (memory operand like `[x0]`/`(%rax)`, or an immediate
/// literal like `#42`/`$42`). The formatter chooses between them at
/// substitution time — `mem` wins if set.
#[derive(Debug, Clone)]
pub struct AsmOperandSlot<R> {
    /// Physical register if the operand resolved to a register-class
    /// substitution; `None` otherwise.
    pub reg: Option<R>,
    /// Pre-formatted memory or immediate operand string; `None` if
    /// the operand is a plain register.
    pub mem: Option<String>,
    /// Operand size in bits. Used by the formatter for sized register
    /// modifiers (`%w0`/`%x0` on aarch64, `%b0`/`%w0`/`%k0`/`%q0` on
    /// x86_64) and as a default for unmodified register formatting.
    pub size: u32,
    /// GCC named-operand alias (e.g. the `[out]` in `%[out]`). `None`
    /// for positional `%0`/`%1`/... operands.
    pub name: Option<String>,
}

/// Substitute `%N`, `%[name]`, `%lN`, `%l[name]`, and size modifiers in
/// an asm template. Architecture-specific register formatting is handled
/// via the [`AsmOperandFormatter`] trait.
///
/// Handles:
/// - `%%` escape sequences -> `%`
/// - `%N` numeric operand references (multi-digit supported)
/// - `%[name]` named operand references
/// - `%lN` and `%l[name]` goto label references
/// - `%{modifier}N` and `%{modifier}[name]` sized register references
pub fn substitute_asm_operands<F: AsmOperandFormatter>(
    formatter: &F,
    template: &str,
    slots: &[AsmOperandSlot<F::Reg>],
    goto_labels: &[(String, String)],
) -> String {
    let mut result = String::with_capacity(template.len() * 2);
    let mut chars = template.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '%' {
            match chars.peek() {
                Some('%') => {
                    // %% -> %
                    chars.next();
                    result.push('%');
                }
                Some('[') => {
                    // %[name] - named operand reference
                    chars.next(); // consume '['
                    let mut name = String::new();
                    while let Some(&ch) = chars.peek() {
                        if ch == ']' {
                            chars.next();
                            break;
                        }
                        name.push(ch);
                        chars.next();
                    }
                    // Look up the name in operand slots
                    if let Some(idx) = slots
                        .iter()
                        .position(|s| s.name.as_deref() == Some(name.as_str()))
                    {
                        let slot = &slots[idx];
                        if let Some(ref mem) = slot.mem {
                            result.push_str(mem);
                        } else if let Some(reg) = slot.reg {
                            result.push_str(&formatter.format_reg_default(reg, slot.size));
                        }
                    } else {
                        // Unknown name, pass through
                        result.push_str("%[");
                        result.push_str(&name);
                        result.push(']');
                    }
                }
                Some(&d) if d.is_ascii_digit() => {
                    // %0, %1, %10, etc. - numeric operand reference (multi-digit supported)
                    chars.next();
                    let mut num_str = String::new();
                    num_str.push(d);
                    while let Some(&digit) = chars.peek() {
                        if digit.is_ascii_digit() {
                            num_str.push(digit);
                            chars.next();
                        } else {
                            break;
                        }
                    }
                    let idx: usize = num_str.parse().unwrap_or(0);
                    if let Some(slot) = slots.get(idx) {
                        if let Some(ref mem) = slot.mem {
                            result.push_str(mem);
                        } else if let Some(reg) = slot.reg {
                            result.push_str(&formatter.format_reg_default(reg, slot.size));
                        }
                    } else {
                        // Unknown operand, pass through
                        result.push('%');
                        result.push_str(&num_str);
                    }
                }
                Some('l') => {
                    // %l - label reference for asm goto: %l0, %l1, %l[name]
                    chars.next(); // consume 'l'
                    if let Some(&next_ch) = chars.peek() {
                        if next_ch == '[' {
                            // %l[name] - named label reference
                            chars.next(); // consume '['
                            let mut name = String::new();
                            while let Some(&ch) = chars.peek() {
                                if ch == ']' {
                                    chars.next();
                                    break;
                                }
                                name.push(ch);
                                chars.next();
                            }
                            // Look up label by name (label_string, label_name)
                            if let Some((label_str, _)) =
                                goto_labels.iter().find(|(_, n)| n == &name)
                            {
                                result.push_str(label_str);
                            } else {
                                // Unknown label, pass through
                                result.push_str("%l[");
                                result.push_str(&name);
                                result.push(']');
                            }
                        } else if next_ch.is_ascii_digit() {
                            // `%lN`: gcc numbers labels after every operand,
                            // the hidden inputs of `"+"` outputs included, so
                            // the first label of a statement with three
                            // operands is `%l3`. Counting from zero, and one
                            // digit at a time, named the wrong label or none.
                            let mut num = String::new();
                            while let Some(&d) = chars.peek() {
                                if !d.is_ascii_digit() {
                                    break;
                                }
                                num.push(d);
                                chars.next();
                            }
                            let label = num
                                .parse::<usize>()
                                .ok()
                                .and_then(|n| n.checked_sub(slots.len()))
                                .and_then(|i| goto_labels.get(i));
                            if let Some((label_str, _)) = label {
                                result.push_str(label_str);
                            } else {
                                // Not a label: pass through for the assembler
                                // to reject, as gcc does.
                                result.push_str("%l");
                                result.push_str(&num);
                            }
                        } else {
                            // Just %l without number or name, pass through
                            result.push_str("%l");
                        }
                    } else {
                        result.push_str("%l");
                    }
                }
                Some(&d) if formatter.size_modifiers().contains(&d) => {
                    // Size modifier: %b0, %w0, %k0, %q0 (x86) or %w0, %x0 (aarch64)
                    chars.next();
                    let size_mod = d;
                    if let Some(&next_ch) = chars.peek() {
                        if next_ch == '[' {
                            // %b[name], %w[name], etc.
                            chars.next(); // consume '['
                            let mut name = String::new();
                            while let Some(&ch) = chars.peek() {
                                if ch == ']' {
                                    chars.next();
                                    break;
                                }
                                name.push(ch);
                                chars.next();
                            }
                            if let Some(idx) = slots
                                .iter()
                                .position(|s| s.name.as_deref() == Some(name.as_str()))
                            {
                                let slot = &slots[idx];
                                if let Some(ref mem) = slot.mem {
                                    result.push_str(mem);
                                } else if let Some(reg) = slot.reg {
                                    result.push_str(&formatter.format_reg_sized(reg, size_mod));
                                }
                            } else {
                                result.push('%');
                                result.push(size_mod);
                                result.push('[');
                                result.push_str(&name);
                                result.push(']');
                            }
                        } else if next_ch.is_ascii_digit() {
                            chars.next();
                            let mut num_str = String::new();
                            num_str.push(next_ch);
                            while let Some(&digit) = chars.peek() {
                                if digit.is_ascii_digit() {
                                    num_str.push(digit);
                                    chars.next();
                                } else {
                                    break;
                                }
                            }
                            let idx: usize = num_str.parse().unwrap_or(0);
                            if let Some(slot) = slots.get(idx) {
                                if let Some(ref mem) = slot.mem {
                                    result.push_str(mem);
                                } else if let Some(reg) = slot.reg {
                                    result.push_str(&formatter.format_reg_sized(reg, size_mod));
                                }
                            } else {
                                result.push('%');
                                result.push(size_mod);
                                result.push_str(&num_str);
                            }
                        } else {
                            result.push('%');
                            result.push(size_mod);
                        }
                    } else {
                        result.push('%');
                        result.push(size_mod);
                    }
                }
                _ => {
                    result.push('%');
                }
            }
        } else {
            result.push(c);
        }
    }

    result
}

// CodeGenerator Trait

/// Trait for architecture-specific code generators
pub trait CodeGenerator {
    /// Generate assembly code for the given IR module
    fn generate(&mut self, module: &Module, types: &TypeTable) -> String;

    /// Set whether to emit basic unwind tables (cfi_startproc/cfi_endproc)
    fn set_emit_unwind_tables(&mut self, emit: bool);

    /// Set position-independent code mode (for shared libraries and PIE)
    fn set_pic_mode(&mut self, pic: bool);

    /// Set shared library mode (for TLS model selection)
    /// In shared library mode, TLS uses Initial Exec/General Dynamic model.
    /// In PIE/executable mode, TLS uses Local Exec for local variables.
    fn set_shared_mode(&mut self, shared: bool);

    /// Set `-fverbose-asm`: annotate the generated instructions.
    fn set_verbose_asm(&mut self, verbose: bool);
}

/// The alignment, in bytes, a global definition is emitted at: an explicit
/// `_Alignas`/`aligned` if it has one, else its type's, and at least 16 for an
/// array of 16 bytes or more (clang's choice, which vector code relies on).
///
/// The one rule, read both where the definition is emitted and where a
/// backend decides whether an access can assume that alignment.
pub fn global_alignment(global: &crate::ir::GlobalDef, types: &TypeTable) -> u32 {
    let size = types.size_bytes(global.typ) as u64;
    let size = if size == 0 { 8 } else { size };
    let mut align = global
        .explicit_align
        .unwrap_or_else(|| types.alignment(global.typ) as u32);
    if matches!(types.get(global.typ).kind, crate::types::TypeKind::Array) && size >= 16 {
        align = align.max(16);
    }
    align
}

/// Report a thread-local that reaches the backend as a plain symbol when the
/// target's model is a call.
///
/// Under the ELF descriptor model and on Mach-O, `ir::tls` gives every
/// thread-local reference an explicit `TlsAddr`, which is what lets the
/// register allocator see the call. A thread-local named anywhere else --
/// in `src` or in an inline-asm operand -- would be reached by a backend path
/// that either emits the call invisibly to the allocator, which destroys
/// whatever it had placed in the clobbered registers, or, on Darwin, a plain
/// non-thread-local reference. An inline-asm memory operand did exactly the
/// first on Linux `-fPIC`. So the contract is checked, and a breach is an
/// internal error rather than wrong code.
pub fn check_tls_reached_only_by_address(
    func: &Function,
    tls_symbols: &std::collections::HashSet<String>,
    pos: crate::diag::Position,
) {
    for insn in func.blocks.iter().flat_map(|b| &b.insns) {
        if insn.op == Opcode::TlsAddr {
            continue;
        }
        for id in insn.mentioned() {
            let Some(crate::ir::PseudoKind::Sym(name)) = func.get_pseudo(id).map(|p| &p.kind)
            else {
                continue;
            };
            // A local whose name collides with a thread-local is a stack slot.
            if tls_symbols.contains(name) && !func.locals.contains_key(name) {
                crate::diag::error_args(
                    pos,
                    "internal error: the thread-local '{0}' reached code generation \
                     without its address being computed",
                    &[name],
                );
                return;
            }
        }
    }
}

/// The current function's pseudos, looked up by id.
///
/// A pseudo's id is not its position in `Function::pseudos`, so a lookup
/// needs the index; finding one by scanning made every constant the backends
/// emitted cost a pass over all of them.
#[derive(Default)]
pub struct PseudoTable {
    by_id: std::collections::HashMap<PseudoId, Pseudo>,
}

impl PseudoTable {
    pub fn new(pseudos: &[Pseudo]) -> Self {
        let mut by_id = std::collections::HashMap::with_capacity(pseudos.len());
        for p in pseudos {
            // The first, as a scan would have found.
            by_id.entry(p.id).or_insert_with(|| p.clone());
        }
        Self { by_id }
    }

    pub fn get(&self, id: PseudoId) -> Option<&Pseudo> {
        self.by_id.get(&id)
    }

    /// Does `id` name a symbol -- an object's storage -- rather than a value?
    pub fn is_sym(&self, id: PseudoId) -> bool {
        self.get(id)
            .is_some_and(|p| matches!(p.kind, crate::ir::PseudoKind::Sym(_)))
    }
}

/// The `-fverbose-asm` annotation for one IR instruction: what it came from.
///
/// gcc writes the operands' source-level names, and the source line beside the
/// instructions it produced. `Pseudo::name` carries the variable a pseudo came
/// from, when it came from one, which is the same information.
pub fn verbose_annotation(insn: &Instruction, pseudos: &PseudoTable) -> Option<String> {
    let name_of = |id: PseudoId| -> Option<&str> {
        pseudos
            .get(id)
            .and_then(|p| p.name.as_deref())
            .filter(|n| !n.is_empty())
    };

    let mut parts: Vec<String> = Vec::new();
    if let Some(t) = insn.target.and_then(name_of) {
        parts.push(t.to_string());
    }
    let srcs: Vec<&str> = insn.src.iter().filter_map(|s| name_of(*s)).collect();
    if !srcs.is_empty() {
        parts.push(srcs.join(", "));
    }
    if let Some(name) = &insn.func_name {
        parts.push(name.clone());
    }

    // An instruction naming nothing the source wrote still says which
    // operation it is; a bare opcode is more use than a blank comment.
    if parts.is_empty() {
        return Some(format!("{:?}", insn.op).to_lowercase());
    }
    Some(parts.join(" <- "))
}

/// The assembler's comment introducer for `target`.
///
/// x86-64 gas takes `#`; aarch64 gas takes `//`, and reads a *trailing* `#` as
/// the start of an immediate -- so this is a correctness requirement of any
/// trailing annotation, not a cosmetic one.
pub fn asm_comment_prefix(target: &Target) -> &'static str {
    match target.arch {
        crate::target::Arch::Aarch64 => "//",
        _ => "#",
    }
}

/// Create a code generator for the given target
pub fn create_codegen(
    target: Target,
    emit_unwind_tables: bool,
    pic_mode: bool,
    shared_mode: bool,
    verbose_asm: bool,
) -> Box<dyn CodeGenerator> {
    use crate::target::Arch;

    let mut codegen: Box<dyn CodeGenerator> = match target.arch {
        Arch::X86_64 => Box::new(super::x86_64::codegen::X86_64CodeGen::new(target)),
        Arch::Aarch64 => Box::new(super::aarch64::codegen::Aarch64CodeGen::new(target)),
    };
    codegen.set_emit_unwind_tables(emit_unwind_tables);
    codegen.set_pic_mode(pic_mode);
    codegen.set_shared_mode(shared_mode);
    codegen.set_verbose_asm(verbose_asm);
    codegen
}
