pub struct CommandSettings {
    pub is_A_all_excluding_current_parent: bool,
    pub is_C_multicolumn_sorted_down: bool,
    pub is_F_do_not_follow_symbolic_links: bool,
    pub is_R_recursive: bool,
    pub is_S_sort_by_filesize: bool,
    pub is_a_all_including_current_parent: bool,
    pub is_c_use_time_of_last_modification: bool,
    pub is_d: bool,
    pub is_f_sort_by_system_order: bool,
    pub is_g_hide_user: bool,
    pub is_k_set_blocksize: bool,
    pub is_i_show_inode: bool,
    pub is_l_long: bool,
    pub is_m_stream_output: bool,
    pub is_n_numeric_gid_uid: bool,
    pub is_o_hide_group: bool,
    pub is_p_add_slash: bool,
    pub is_q_force_nonprintable_as_questionmarks: bool,
    pub is_r_reverse_sort_order: bool,
    pub is_s_show_system_blocks: bool,
    pub is_t_sort_by_time_modified: bool,
    pub is_u_use_time_of_last_access: bool,
    pub is_x_multicolumn_sorted_across: bool,
    pub is_1_single_line_output: bool,
}
